### ISSUE TITLE
CR: remove required PDF from Compostitions others than Prescription and Medication Card (Walter Wellauer, Cistec AG)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-emed#28]
ch.fhir.ig.ch-emed#0.2.0 /

originalRespresentation/entry 1..1	Reference(Binary)PDF only for Mediaction Card Compostition and Medication Prescription prescrition, in all others only 0..1 Reference(Binary)PDF as they are only transactional documents. Following IHE PHARM, the Consumer only reads a consolidated view (medication card) or a prescription

Walter Wellauer, Cistec AG

**Comment by walterwellauer** [comment]
The Status Change of a medication according to http://fhir.ch/ig/ch-emed/ValueSet-ihe-pharmaceuticaladvicestatuslist.html doesn't produce a document in the primary system, but is achieved through UI interaction.
Changes in his medication can always be perceived by the patient through a view of his actual medication (medication card document).
The actual requirement of providing a pdf for UI interaction is a de facto audit message which should achieved by other means (preferrably by proper auditing messages whisch are already provided in the EPR context)

**Comment by eHealth-Suisse** [comment]
agree.
see also #29  
and outcome of discussion during eMed Projectathon, :
"outcome of break-out session: https://pat.chat.ihe-europe.net/group/news?msg=xNDk5daeTPYcpYETf 
- for a start, PDF representation should only be required on Medication Card document which is also the first document to enter the EPR legal framework
- what this PDF has to include (at minimum) should be defined, probably in discussion with interprofessional group IPAG
- for the other documents (as Pharmaceutical Advice, MTP, etc.) this will be discussed and decided later on, together with discussions on architecture"
Since the Orig.representation on the Prescription document is undisputed, it will be kept there as well.

**Comment by oliveregger** [comment]
@ziegm : könntest Du noch die übersichtsgrafiken mit den bildern für die dokumente anpassen und dort die grüne section originalRespresentation entfernen?

http://build.fhir.org/ig/ehealthsuisse/ch-emed/medication-treatment-plan-document.html
http://build.fhir.org/ig/ehealthsuisse/ch-emed/medication-dispense-document.html
http://build.fhir.org/ig/ehealthsuisse/ch-emed/pharmaceutical-advice-document.html
http://build.fhir.org/ig/ehealthsuisse/ch-emed/medication-list-document.html
