### ISSUE TITLE
Abbildung Rezept: Wiederholter Bezug pro Arzneimittel (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ziegm** [ehealthsuisse/ch-emed#76]
Im Fallbeispiel für die [Prescription (2-6)](http://fhir.ch/ig/ch-emed/usecase-german.html) wird folgendes beschrieben:
**Wiederholter Bezug pro Arzneimittel: Dauerrezept für 3 Monate**

Das [Beispieldokument](http://fhir.ch/ig/ch-emed/Bundle-2-6-MedicationPrescription.json.html) beinhaltet folgende Angaben:
```json
        "dispenseRequest" : {
          "numberOfRepeatsAllowed" : 2,
          "quantity" : {
            "value" : 1
          }
        }
```

Diese Werte im Beispieldokument sagen nicht dasselbe aus, wie das was im Anwendungsfall beschrieben ist. Aus meiner Sicht ist zu klären, was unter **Wiederholter Bezug pro Arzneimittel** (aus [IPAG](https://www.e-health-suisse.ch/fileadmin/user_upload/Dokumente/2017/D/170607_Bericht_eMedikation_IPAG.pdf) Minimaldatenset) zu verstehen ist. Eine Gültigkeit in Monaten oder Anzahl Wdh.

**Comment by ziegm** [comment]
Analyse mit HCI

Wiederholungen bei einem Rezept (3 Möglichkeiten)

1. Dauerrezept mit Monaten angegeben (z.B. 3 Monate gültig)
2. Anzahl der Repetitionen angeben (2 Repetitionen, total 2x einlösen oder 3x einlösen? -> HCI klärt noch ab)
3. Spezialfall: Medikament darf max. 5x bezogen werden

**Comment by pjolo** [comment]
Erste Rückmeldung IPAG:


- Das Konzept eines «Dauerrezept» ist oft implizit. Die Apotheker kennen die Medikamente welche bei chronischen Krankheiten zur Anwendung kommen. Im Gesetz (HMG?) ist festgehalten, dass Apotheker Dauer-Medikationen bis zu 12 Monaten selbständig und ohne Erneuerung des Rezepts, bzw. Rückfrage bei der verschreibenden Gesundheitsfachperson, abgeben können. Nach 12 Monaten ist ein erneuter (Kontroll-)Besuch beim Arzt mit einer Erneuerung des Rezepts verbunden. Üblicherweise ist die Angabe wie folgt: «Medikation X für 3 Mte, 3 Repetitionen», dies ergibt einen totale Dauer von 12 Monaten. 

- Es wäre wünschenswert, dass dies in einer expliziten Formulierung, die auch heute manchmal gebraucht wird, angegeben wird, so wie es im Beispiel unten aufgeführt wird. D.h., dass die initiale Verschreibung eines Medikaments für eine begrenzte Zeit gemacht wird (z.B. 3 Monate) und dann angegeben wird, dass 3 Repetitionen möglich sind (für ein total von 12 Mte). Ohne Repetitionsangabe liegt es im Ermessen des Apothekers was er/sie tun kann. Bei gewissen Medikationen (-klassen) muss explizit angegeben werden, ob Repetitionen und wie viele, oder keine (Betäubungsmittel, etc.).

- Das Beispiel ist etwas unglücklich formuliert: Angabe von Dauermedikation (ja/nein) und Repetition (Anzahl, numerisch: «0» default) sollten/könnten getrennte Felder sein, da es verschiedene Kombinationen erlaubt. Z.B. ist es möglich: keine Dauermedikation, Dauer 30 Tage, und 1 Repetition. Im Beispiel, hätte die Anwendungsdauer als «3 Monate», «wiederholter Bezug = 3», und «Dauermedikation = 1», angegeben werden können, obwohl dies eine gewisse Redundanz hat. 

- Das Feld "Dauerrezept" hat nichts mit dem Verlängerungszeitraum (rot) zu tun, sondern gibt nur an, dass wiederholte Abgaben möglich sind. Die totale Dauer ergibt sich aus dem Feld «Anwendungsdauer» und Anzahl Repetitionen.

Weitere Abklärung werden intern bei IPAG noch gemacht.

**Comment by ziegm** [comment]
# Stand 24.11.2021

## Übersichtsgrafik aus IHE Pharmacy
**Blauer Balken:** Gültigkeitsdauer des Rezeptes (innerhalb welcher Frist dürfen die Medikamente bezogen werden)
**Schwarze Pfeile (t2/t3/t4):** Repetierbarkeit (Anzahl der Wiederholungen)
![image](https://user-images.githubusercontent.com/32767151/143228398-26b5e2d4-080a-44ac-9a41-5702eacefc49.png)

## Diskrepanz zwischen IPAG und HCI?
- HCI
   - Variante 1: 3 Monate -> Ab Ausstellungsdatum des Rezepts kann das Medi 3 Monate lang bezogen werden (blauer Balken)
   - Variante 2: Anzahl Repetitionen (schwarze Pfeile, t2/t3/t4) 
- IPAG
   - Die totale Dauer ergibt sich aus dem Feld «Anwendungsdauer» und Anzahl Repetitionen.
- Fazit
   - Dauer bezieht sich bei beiden auf die Gültigkeitsdauer eines Rezepts  
   - HCI versteht die Repetitionen auf die Anzahl Abgaben der Medikation und IPAG auf die Anzahl Wiederholungen des Rezepts

**Comment by qligier** [comment]
I've discussed this part of the CDA specifications recently with Stéphane, it's not simple :) 

> **Blauer Balken:** Gültigkeitsdauer des Rezeptes (innerhalb welcher Frist dürfen die Medikamente bezogen werden) 

It's indeed the validity period of the medication, but may or may not be the period during which the medication can be obtained (see thereafter). It's the period over which the patient may be taking the medication (but not to be considered as an intake period instructions for the patient).

> **Schwarze Pfeile (t2/t3/t4):** Repetierbarkeit (Anzahl der Wiederholungen) 

t2 and t3 are dispenses, t4 is the end of the renewal period.

The **renewal period** may be specified to restrict the period over which the medication may be re-dispensed. If the period is relative (e.g. 1 month) instead of absolute (known date boundaries), then it starts at the initial dispense, not at the start of the prescription validity period.

The **repeat number** may be used to restrict the number of times the prescription may be re-dispensed in its original quantity (excluding the initial dispense). E.g. a prescription for 20 tablets with a repeat number of 4 means that 100 tablets in total may be dispensed.

Both should probably not be used at the same time (we were unable to find a use case where it may make sense).

> HCI versteht die Repetitionen auf die Anzahl Abgaben der Medikation und IPAG auf die Anzahl Wiederholungen des Rezepts

IPAG is right, HCI may be right if they consider dispenses of the original quantity only. I don't know what the law says, but as long pharmacists re-dispense the initial quantity only, both definitions seems equal to me.

> * 6.3.2.1 **Validity of document** (S. 20) -> blue
>   * CDA: documentationOf
>     * While the "documentationOf" element defines the validity of the Community Prescription document, content elements “repeat number” and “renewal period” control the possible renewal of the dispense of the prescription as show in the figure.
>   * CH EMED: [MedicationRequest.dispenseRequest.validityPeriod](http://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-medicationrequest-definitions.html#MedicationRequest.dispenseRequest.validityPeriod)

The _MedicationRequest.dispenseRequest.validityPeriod_ lower bound is the lower bound of the documentationOf, the higher bound is either the higher bound of the renewal period (if it's specified) or the documentationOf.

> * 6.3.4.2.3.21 **Renewal Period** (S. 43) / 6.3.4.14 Renewal Period Content Module (1.3.6.1.4.1.19376.1.9.1.3.15) (S. 71) -> red
>   * CDA: renewal period
>     
>     * Renewal Period Content Module describes the possible renewal of a Prescription Item in terms
>       of duration or period of time (start / end date).
>   * CH EMED: [MedicationRequest.dispenseRequest.expectedSupplyDuration](http://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-medicationrequest-definitions.html#MedicationRequest.dispenseRequest.expectedSupplyDuration)
>     
>     * Identifies the period time over which the supplied product is expected to be used, or the length of time the dispense is expected to last.

This mapping appears wrong to me. The _expectedSupplyDuration_ seems closer to either the PRE document _documentationOf_ or the PRE item _effectiveTime_.

The CDA and FHIR concepts seems to be quite different.

**Comment by ziegm** [comment]
Summary of final changes:
* Update [CH EMED MedicationRequest Profile](http://build.fhir.org/ig/ehealthsuisse/ch-emed/branches/repeated-purchase/StructureDefinition-ch-emed-medicationrequest.html)
   *  Set minimum cardinality for element `MedicationRequest.dispenseRequest.numberOfRepeatsAllowed` (and `MedicationRequest.dispenseRequest`) back to 0, according to changes in CDA.

**Comment by ziegm** [comment]
@pjolo 
- Please add the summary of the meeting (15.12.2021) with HCI and IPAG here.
- Please check, if the current representation in the IG corresponds to the outcome of the meeting. ([Summary of changes](https://github.com/ehealthsuisse/ch-emed/issues/76#issuecomment-996540744) described above.)
- Please check with Stéphane and/or Quentin.
- If everything is okay, please merge this [PR](https://github.com/ehealthsuisse/ch-emed/pull/87) and close the issue.

**Comment by pjolo** [comment]
In the meeting of 15.12.21 the issue was discussed with IPAG and HCI.
For a permanent prescription, the number of doses is converted into number of tablets. The number of tablets is in turn converted to the number of packages. In Example 2-6, two tablets are used per day, which results in 180 tablets for the three months. These 180 tablets are converted into the number of packs that the patient is allowed to take during these three months. So this is in line with the conclusion of HCI that the repetitions are related to the number of medications.
